FROM oven/bun:1.4.2-alpine

WORKDIR /app
COPY package.json bun.lock .bun-version ./
COPY apps ./apps
COPY packages ./packages

RUN bun install --frozen-lockfile --production --ignore-scripts

ENV PORT=3001
EXPOSE 3001
CMD ["bun", "run", "apps/server/src/index.ts"]
